### ISSUE TITLE
Broken binary in platform

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-platform#893]
### Issue description

<img width="1132" alt="CleanShot 2023-08-31 at 18 27 47@2x" src="https://github.com/micronaut-projects/micronaut-platform/assets/864788/cf25138d-9b86-45d9-b0e6-2f6335bc1ac4">

I did this in Micronaut Data https://github.com/micronaut-projects/micronaut-data/commit/aa4f7dc0d13a35b746e16a41044f2141c666d146

**Comment by timyates** [comment]
I'm going to close this as I believe it's fixed by the 4.1.1 data release
